# Generated by Django 5.2 on 2025-04-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=50)),
                ('Gmail', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
