# Generated by Django 5.2 on 2025-04-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datas',
            old_name='Adress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='datas',
            old_name='Name',
            new_name='NAME',
        ),
    ]
