# Generated by Django 5.2 on 2025-04-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treat', '0002_rename_adress_datas_address_rename_name_datas_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Address',
            field=models.CharField(max_length=255),
        ),
    ]
