# Generated by Django 5.2 on 2025-04-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treat', '0003_alter_datas_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
